services:
  db-roberto-8305:
    image: postgres:latest
    restart: always
    tty: true
    container_name: db-roberto-8305
    volumes:
      - ./Docker-Compose/PostgreSQL:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=seletivo
    networks:
      - mynetwork
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      retries: 5
      start_period: 10s

  minio-roberto-8305:
    build:
      context: ./minio
      dockerfile: Dockerfile
    container_name: minio-roberto-8305
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: seletivo123@
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always
    networks:
      - mynetwork

  api-processo-seletivo:
    build: ../app
    container_name: api-processo-seletivo
    restart: always
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db-roberto-8305:5432/seletivo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      S3_URL: http://minio-roberto-8305:9000
      S3_URL_PUBLIC: http://localhost:9003/minio
      S3_ACCESS_KEY: admin
      S3_ACCESS_SECRET: seletivo123@
    depends_on:
      db-roberto:
        condition: service_healthy
      minio-roberto:
        condition: service_started
    networks:
      - mynetwork

  nginx-roberto-8305:
    image: nginx:latest
    container_name: nginx-roberto-8305
    ports:
      - "9003:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - minio-roberto-8305
    restart: always
    networks:
      - mynetwork

volumes:
  minio_data:
    driver: local

networks:
  mynetwork:
    driver: bridge
