spring:
  jackson:
    date-format: "dd/MM/yyyy"
    serialization:
      write-dates-as-timestamps: false
  servlet:
    multipart:
      max-file-size: 10GB # Max file size.
      max-request-size: 100GB # Max request size.
  datasource:
    url: jdbc:postgresql://${DB_URL:localhost:5432}/${DB_URL_SCHEMA:seletivo}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      auto-commit: false
      connection-timeout: 250
      max-lifetime: 600000
      maximum-pool-size: 20
      minimum-idle: 10
      pool-name: master
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      "[hibernate.dialect]": org.hibernate.dialect.PostgreSQLDialect
      "[hibernate.generate_statistics]": false
      "[hibernate.connection.provider_disables_autocommit]": true

seletivo:
  swagger:
    url: http://localhost:8083
  s3:
    url: ${S3_URL:http://localhost:9000}
    urlPublic: ${S3_URL_PUBLIC:http://localhost:9003}
    access-key: ${S3_ACCESS_KEY:admin}
    access-secret: ${S3_ACCESS_SECRET:seletivo123@}
    bucket-name: ${S3_BUCKET_NAME:fotos}
  user:
    username: admin
    password: password
server:
  port: 8083
  servlet:
    context-path: /apiseletivo
application:
  titulo: API Seletivo
  autor: Roberto de Souza Xavier Junior
  minio: Console minio - http://localhost:9001
  swagger: Endereco do Swagger - http://localhost:8083/apiseletivo/swagger-ui/index.html#/
springdoc:
  swagger-ui:
    operations-sorter: method
    tags-sorter: alpha
